# DataSource Config
spring:
  #配置发送信息
  mail:
    host: smtp.qq.com
    username: 1442068370@qq.com
    password: fwxdqtrlhgugjicc
    port: 25
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smth:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharing_web?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  devtools:
    livereload:
      port: 37512
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8081
jy:
  jwt:
    #加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长
    expire: 604800
    header: Authorization